package com.wchgogo.m3u8downloader.mapper;

import com.wchgogo.m3u8downloader.po.TaskDetail;
import com.wchgogo.m3u8downloader.po.TaskDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    int countByExample(TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    int deleteByExample(TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    int deleteByPrimaryKey(Long detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    int insert(TaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    int insertSelective(TaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    List<TaskDetail> selectByExample(TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    TaskDetail selectByPrimaryKey(Long detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") TaskDetail record, @Param("example") TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    int updateByExample(@Param("record") TaskDetail record, @Param("example") TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    int updateByPrimaryKeySelective(TaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    int updateByPrimaryKey(TaskDetail record);
}