package com.wchgogo.m3u8downloader.po;

public class Task {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_id
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.url
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.filename
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.format
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    private String format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.thread_num
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    private Integer threadNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.retry_time
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    private Integer retryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.state
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.create_time
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.finish_time
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    private Long finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.elapse_time
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    private Long elapseTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_id
     *
     * @return the value of task.task_id
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_id
     *
     * @param taskId the value for task.task_id
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.url
     *
     * @return the value of task.url
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.url
     *
     * @param url the value for task.url
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.filename
     *
     * @return the value of task.filename
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.filename
     *
     * @param filename the value for task.filename
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.format
     *
     * @return the value of task.format
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.format
     *
     * @param format the value for task.format
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public void setFormat(String format) {
        this.format = format == null ? null : format.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.thread_num
     *
     * @return the value of task.thread_num
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public Integer getThreadNum() {
        return threadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.thread_num
     *
     * @param threadNum the value for task.thread_num
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public void setThreadNum(Integer threadNum) {
        this.threadNum = threadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.retry_time
     *
     * @return the value of task.retry_time
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public Integer getRetryTime() {
        return retryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.retry_time
     *
     * @param retryTime the value for task.retry_time
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public void setRetryTime(Integer retryTime) {
        this.retryTime = retryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.state
     *
     * @return the value of task.state
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.state
     *
     * @param state the value for task.state
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.create_time
     *
     * @return the value of task.create_time
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.create_time
     *
     * @param createTime the value for task.create_time
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.finish_time
     *
     * @return the value of task.finish_time
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public Long getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.finish_time
     *
     * @param finishTime the value for task.finish_time
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public void setFinishTime(Long finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.elapse_time
     *
     * @return the value of task.elapse_time
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public Long getElapseTime() {
        return elapseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.elapse_time
     *
     * @param elapseTime the value for task.elapse_time
     *
     * @mbggenerated Mon Apr 06 23:00:54 CST 2020
     */
    public void setElapseTime(Long elapseTime) {
        this.elapseTime = elapseTime;
    }
}