package com.wchgogo.m3u8downloader.po;

public class Task {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_id
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.url
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.filename
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.format
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    private String format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.thread_num
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    private Integer threadNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.retry_time
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    private Integer retryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.state
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.fail_reason
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    private String failReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.create_time
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.start_time
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    private Long startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.finish_time
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    private Long finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.elapse_time
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    private Long elapseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.total_segments
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    private Integer totalSegments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.finish_segments
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    private Integer finishSegments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_id
     *
     * @return the value of task.task_id
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_id
     *
     * @param taskId the value for task.task_id
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.url
     *
     * @return the value of task.url
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.url
     *
     * @param url the value for task.url
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.filename
     *
     * @return the value of task.filename
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.filename
     *
     * @param filename the value for task.filename
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.format
     *
     * @return the value of task.format
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.format
     *
     * @param format the value for task.format
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public void setFormat(String format) {
        this.format = format == null ? null : format.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.thread_num
     *
     * @return the value of task.thread_num
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public Integer getThreadNum() {
        return threadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.thread_num
     *
     * @param threadNum the value for task.thread_num
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public void setThreadNum(Integer threadNum) {
        this.threadNum = threadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.retry_time
     *
     * @return the value of task.retry_time
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public Integer getRetryTime() {
        return retryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.retry_time
     *
     * @param retryTime the value for task.retry_time
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public void setRetryTime(Integer retryTime) {
        this.retryTime = retryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.state
     *
     * @return the value of task.state
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.state
     *
     * @param state the value for task.state
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.fail_reason
     *
     * @return the value of task.fail_reason
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public String getFailReason() {
        return failReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.fail_reason
     *
     * @param failReason the value for task.fail_reason
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public void setFailReason(String failReason) {
        this.failReason = failReason == null ? null : failReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.create_time
     *
     * @return the value of task.create_time
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.create_time
     *
     * @param createTime the value for task.create_time
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.start_time
     *
     * @return the value of task.start_time
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.start_time
     *
     * @param startTime the value for task.start_time
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.finish_time
     *
     * @return the value of task.finish_time
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public Long getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.finish_time
     *
     * @param finishTime the value for task.finish_time
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public void setFinishTime(Long finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.elapse_time
     *
     * @return the value of task.elapse_time
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public Long getElapseTime() {
        return elapseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.elapse_time
     *
     * @param elapseTime the value for task.elapse_time
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public void setElapseTime(Long elapseTime) {
        this.elapseTime = elapseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.total_segments
     *
     * @return the value of task.total_segments
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public Integer getTotalSegments() {
        return totalSegments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.total_segments
     *
     * @param totalSegments the value for task.total_segments
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public void setTotalSegments(Integer totalSegments) {
        this.totalSegments = totalSegments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.finish_segments
     *
     * @return the value of task.finish_segments
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public Integer getFinishSegments() {
        return finishSegments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.finish_segments
     *
     * @param finishSegments the value for task.finish_segments
     *
     * @mbggenerated Sat Apr 11 21:49:11 CST 2020
     */
    public void setFinishSegments(Integer finishSegments) {
        this.finishSegments = finishSegments;
    }
}