package com.wchgogo.m3u8downloader.po;

public class TaskDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.detail_id
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    private Long detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.task_id
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.segment_url
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    private String segmentUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.retry_times
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    private Integer retryTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.state
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.detail_id
     *
     * @return the value of task_detail.detail_id
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    public Long getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.detail_id
     *
     * @param detailId the value for task_detail.detail_id
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    public void setDetailId(Long detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.task_id
     *
     * @return the value of task_detail.task_id
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.task_id
     *
     * @param taskId the value for task_detail.task_id
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.segment_url
     *
     * @return the value of task_detail.segment_url
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    public String getSegmentUrl() {
        return segmentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.segment_url
     *
     * @param segmentUrl the value for task_detail.segment_url
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    public void setSegmentUrl(String segmentUrl) {
        this.segmentUrl = segmentUrl == null ? null : segmentUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.retry_times
     *
     * @return the value of task_detail.retry_times
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    public Integer getRetryTimes() {
        return retryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.retry_times
     *
     * @param retryTimes the value for task_detail.retry_times
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    public void setRetryTimes(Integer retryTimes) {
        this.retryTimes = retryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.state
     *
     * @return the value of task_detail.state
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.state
     *
     * @param state the value for task_detail.state
     *
     * @mbggenerated Fri May 01 15:21:54 CST 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }
}